name: cohere-toolkit


services:
  test_db:
    image: postgres:14.1-alpine
    restart: unless-stopped
    environment:
      - PGUSER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    networks:
      - proxynet

  redis:
    image: valkey/valkey:8.0-alpine
    restart: always
    healthcheck:
      test: [ "CMD", "valkey-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "6379:6379"
    networks:
      - proxynet
    command: valkey-server --save 60 1 --loglevel warning --requirepass redis
    volumes:
      - ./data:/data

  backend:
    build:
      context: .
      args:
        INSTALL_COMMUNITY_DEPS: true
      dockerfile: ./src/backend/Dockerfile
    develop:
      watch:
        - action: sync
          path: ./src/backend
          target: /workspace/src/backend
          ignore:
            - __pycache__/
            - alembic/
            - data/
        - action: sync
          path: ./src/community
          target: /workspace/src/community
          ignore:
            - __pycache__/
            - alembic/
            - data/
    stdin_open: true
    tty: true
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      # Mount alembic folder to sync migrations
      - ./src/backend/alembic:/workspace/src/backend/alembic
      # Mount configurations
      - ./src/backend/config/secrets.yaml:/workspace/src/backend/config/secrets.yaml
      - ./src/backend/config/configuration.yaml:/workspace/src/backend/config/configuration.yaml
    networks:
      - proxynet
      - supabase_network

  frontend:
    build:
      target: ${BUILD_TARGET:-prod}
      context: ./src/interfaces/coral_web
      dockerfile: Dockerfile
    environment:
      API_HOSTNAME: http://backend:8000
      NEXT_PUBLIC_API_HOSTNAME: ${NEXT_PUBLIC_API_HOSTNAME}
      NEXT_PUBLIC_FRONTEND_HOSTNAME: ${NEXT_PUBLIC_FRONTEND_HOSTNAME}
      NEXT_PUBLIC_GOOGLE_DRIVE_CLIENT_ID: ${NEXT_PUBLIC_GOOGLE_DRIVE_CLIENT_ID}
      NEXT_PUBLIC_GOOGLE_DRIVE_DEVELOPER_KEY: ${NEXT_PUBLIC_GOOGLE_DRIVE_DEVELOPER_KEY}
    restart: always
    networks:
      - proxynet
    ports:
      - 4000:4000
    develop:
      watch:
        - action: sync
          path: ./src/interfaces/coral_web
          target: /app
          ignore:
            - node_modules/

  terrarium:
    image: ghcr.io/cohere-ai/terrarium:latest
    ports:
      - "8080:8080"
    expose:
      - "8080"
    networks:
      - proxynet

volumes:
  db:
    name: cohere_toolkit_db
    driver: local

networks:
  proxynet:
    name: custom_network
  supabase_network:
    external: true
    name: toolkit_supabase_network

